/*
=========================================================
 INARA v2.0
 Module 009 - Recommendations
---------------------------------------------------------
 Description:
 Stores personalized recommendations generated by
 the system, Atlas, teachers or administrators.

 Purpose:
 Support students, improve academic performance
 and reduce dropout risk.
---------------------------------------------------------
 Database: PostgreSQL
=========================================================
*/


-- =====================================================
-- Recommendation Type
-- =====================================================

CREATE TYPE recommendation_type AS ENUM (
    'ACADEMIC',
    'ATTENDANCE',
    'RISK',
    'ATLAS',
    'ACHIEVEMENT',
    'XP',
    'COURSE',
    'MOTIVATION',
    'SYSTEM'
);


-- =====================================================
-- Recommendation Priority
-- =====================================================

CREATE TYPE recommendation_priority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'CRITICAL'
);


-- =====================================================
-- Recommendation Source
-- =====================================================

CREATE TYPE recommendation_source AS ENUM (
    'SYSTEM',
    'ATLAS',
    'TEACHER',
    'ADMIN',
    'AI'
);


-- =====================================================
-- Recommendations Table
-- =====================================================

CREATE TABLE recommendations (

    recommendation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    student_id UUID NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,


    recommendation_type recommendation_type NOT NULL,

    priority recommendation_priority NOT NULL,

    source recommendation_source NOT NULL,


    title VARCHAR(120) NOT NULL,

    message TEXT NOT NULL,


    related_course_id UUID,

    related_risk_id UUID,


    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    is_applied BOOLEAN NOT NULL DEFAULT FALSE,


    expires_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),


    CONSTRAINT fk_recommendation_course
        FOREIGN KEY (related_course_id)
        REFERENCES courses(id)
        ON DELETE SET NULL,


    CONSTRAINT fk_recommendation_risk
        FOREIGN KEY (related_risk_id)
        REFERENCES student_risk(id)
        ON DELETE SET NULL
);



-- =====================================================
-- Indexes
-- =====================================================

CREATE INDEX idx_recommendations_student
ON recommendations(student_id);


CREATE INDEX idx_recommendations_type
ON recommendations(recommendation_type);


CREATE INDEX idx_recommendations_priority
ON recommendations(priority);


CREATE INDEX idx_recommendations_source
ON recommendations(source);


CREATE INDEX idx_recommendations_created_at
ON recommendations(created_at);


CREATE INDEX idx_recommendations_is_read
ON recommendations(is_read);


CREATE INDEX idx_recommendations_course
ON recommendations(related_course_id);


CREATE INDEX idx_recommendations_risk
ON recommendations(related_risk_id);



-- =====================================================
-- Documentation
-- =====================================================

COMMENT ON TABLE recommendations IS
'Stores personalized recommendations generated by INARA to support student success and reduce dropout risk.';


COMMENT ON COLUMN recommendations.student_id IS
'Student receiving the recommendation.';


COMMENT ON COLUMN recommendations.recommendation_type IS
'Category of recommendation generated.';


COMMENT ON COLUMN recommendations.priority IS
'Importance level of the recommendation.';


COMMENT ON COLUMN recommendations.source IS
'Origin of the recommendation: Atlas, system, teacher or administrator.';


COMMENT ON COLUMN recommendations.message IS
'Recommendation content shown to the student.';


COMMENT ON COLUMN recommendations.related_course_id IS
'Associated course related to this recommendation.';


COMMENT ON COLUMN recommendations.related_risk_id IS
'Associated academic risk analysis record.';
